#!/usr/bin/env bash
set -e

here="$(cd "${0%/*}"; pwd)"

for file in "$here"/*; do
  name="$(basename "$file" .md)"
  [[ $name = bin ]] && dotname="$name" || dotname=".${name}"

  if ! [[ "install LICENSE README" =~ $name || $name =~ ".plist" || -e ~/$dotname || -d $file/.git ]]; then
    ln -sfv ${file#$HOME/} "${HOME}/${dotname}"
  fi
done

sudo apt-get install CMake ruby-dev vim-latexsuite texlive-lang-european texlive-font-utils zsh
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
sudo chsh -s `which zsh`
sudo vim-addons -w install latex-suite || echo "Latex suite already installed"
git clone git://github.com/github/hub.git ~/hub || echo "hub already cloned"
cd ~/hub/ && sudo rake install || echo "hub not installed"

echo
echo "Symlinks created."
read -p "Do you want to install vim bundles? [Yy]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then

  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle || echo "Vundle already installed"

  vim +BundleInstall +qall || echo "Cannot install vim bundles"

  cd ~/.vim/bundle/YouCompleteMe
  ./install.sh --clang-completer || echo "Cannot compile YMC"

  vim +BundleInstall +qall || echo "Cannot install all vim bundles"

fi
